
version: '3'

services:
    nginx-api:
        image: nginx
        container_name: nginx-api
        restart: unless-stopped
        volumes:
            - ./routes/nginx-api/:/etc/nginx/conf.d/
        ports:
            - 80:80
        networks:
            pool-network:
                ipv4_address: 172.3.20.2

    


  ################
  # Architecture #
  ################

    nats:
        image: nats
        container_name: nats
        restart: unless-stopped
        networks:
            pool-network:
                ipv4_address: 172.3.200.1

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        networks:
            pool-network:
                ipv4_address: 172.3.200.2
    
    mail-backend:
        image: vivaconagua/mail-backend:latest
        build: ./repos/mail-backend
        container_name: mail-backend
        restart: unless-stopped
        volumes:
            - ./config/mail-backend/config.yml:/go/src/mail-backend/config.yml
        networks:
            pool-network:
                ipv4_address: 172.3.200.3

    mail-dev:
        image: rnwood/smtp4dev:v3
        container_name: mail
        restart: unless-stopped
        networks:
            pool-network:
                ipv4_address: 172.3.220.3

    assets:
        image: vivaconagua/assets:latest
        build: ./repos/assets
        container_name: assets
        restart: unless-stopped
        volumes:
            - ./volumes/assets/:/go/src/assets/public
        networks:
            pool-network:
                ipv4_address: 172.3.220.4
    

    ########
    # Auth #
    ########
    
    auth-backend:
        image: vivaconagua/auth-backend:latest
        build: ./repos/auth-backend
        container_name: auth-backend
        restart: unless-stopped
        volumes:
            - ./config/auth-backend/config.yml:/go/src/auth-backend/config.yml
        networks:
            pool-network:
                ipv4_address: 172.3.100.1
    auth-db:
        image: mysql
        container_name: auth-db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=auth 
            - MYSQL_USER=auth
            - MYSQL_PASSWORD=auth 
            - MYSQL_ROOT_PASSWORD=yes 
        volumes:
            - ./volumes/auth-db/mysql/:/var/lib/mysql/
            - ./repos/auth-backend/db/:/docker-entrypoint-initdb.d/
        networks:
            pool-network:
                ipv4_address: 172.3.150.1
    #############
    # Dispenser #
    #############

    dispenser-backend:
        image: vivaconagua/dispenser-backend:latest
        build: ./repos/dispenser-backend
        container_name: dispenser-backend
        restart: unless-stopped
        networks:
            pool-network:
                ipv4_address: 172.3.100.2

    dispenser-db:
        image: mongo
        container_name: dispenser-database
        restart: always
        volumes: 
            - ./volumes/dispenser-db/mongodb/:/data/db/
        networks:
            pool-network:
                ipv4_address: 172.3.150.2
networks:
    pool-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.3.0.0/16
